version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mediastore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_media_data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - DJANGO_DEBUG=True
      - DB_NAME=mediastore_db
      - DB_USER=postgres
      - DB_PASSWORD=postgrespassword
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations movies &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_media_data:
